const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  COLLECTOR: 'COLLECTOR',
  PROCESSOR: 'PROCESSOR',
  BUYER: 'BUYER',
});

const ORG_ROLES = Object.freeze([ROLES.ORG_ADMIN, ROLES.COLLECTOR, ROLES.PROCESSOR, ROLES.BUYER]);

const WASTE_TRANSITIONS = Object.freeze({
  SUBMITTED: ['UNDER_REVIEW', 'APPROVED', 'REJECTED'],
  UNDER_REVIEW: ['APPROVED', 'REJECTED'],
  APPROVED: ['ASSIGNED'],
  ASSIGNED: ['RECEIVED'],
  RECEIVED: ['PROCESSING'],
  PROCESSING: ['PROCESSED'],
  PROCESSED: ['CONVERTED', 'ARCHIVED'],
  REJECTED: ['ARCHIVED'],
  CONVERTED: ['ARCHIVED'],
  ARCHIVED: [],
});

const PRODUCTION_BATCH_TRANSITIONS = Object.freeze({
  DRAFT: ['IN_PROGRESS', 'CANCELLED'],
  IN_PROGRESS: ['COMPLETED', 'CANCELLED'],
  COMPLETED: [],
  CANCELLED: [],
});

const ORDER_STATUS_TRANSITIONS = Object.freeze({
  PENDING: ['CONFIRMED', 'CANCELLED'],
  CONFIRMED: ['PROCESSING', 'CANCELLED'],
  PROCESSING: ['READY', 'CANCELLED'],
  READY: ['DISPATCHED', 'CANCELLED'],
  DISPATCHED: ['DELIVERED', 'CANCELLED'],
  DELIVERED: [],
  CANCELLED: [],
});

const PAYMENT_STATUS_TRANSITIONS = Object.freeze({
  UNPAID: ['PARTIALLY_PAID', 'PAID', 'FAILED', 'REFUNDED'],
  PARTIALLY_PAID: ['PAID', 'FAILED', 'REFUNDED'],
  PAID: ['REFUNDED'],
  FAILED: ['UNPAID', 'PAID'],
  REFUNDED: [],
});

const DELIVERY_STATUS_TRANSITIONS = Object.freeze({
  PENDING: ['ASSIGNED', 'IN_TRANSIT', 'FAILED'],
  ASSIGNED: ['IN_TRANSIT', 'FAILED'],
  IN_TRANSIT: ['DELIVERED', 'FAILED'],
  DELIVERED: [],
  FAILED: ['ASSIGNED', 'IN_TRANSIT'],
});

const AUDIT_ACTIONS = Object.freeze({
  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
  ORGANIZATION_STATUS_CHANGED: 'ORGANIZATION_STATUS_CHANGED',
  ORG_ADMIN_CREATED: 'ORG_ADMIN_CREATED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  WASTE_CREATED: 'WASTE_CREATED',
  WASTE_STATUS_CHANGED: 'WASTE_STATUS_CHANGED',
  WASTE_ASSIGNED: 'WASTE_ASSIGNED',
  WALLET_ADJUSTED: 'WALLET_ADJUSTED',
  REDEMPTION_CREATED: 'REDEMPTION_CREATED',
  REDEMPTION_REVIEWED: 'REDEMPTION_REVIEWED',
  PRODUCTION_BATCH_CREATED: 'PRODUCTION_BATCH_CREATED',
  PRODUCTION_BATCH_COMPLETED: 'PRODUCTION_BATCH_COMPLETED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  ESG_REPORT_GENERATED: 'ESG_REPORT_GENERATED',
  AI_INSIGHT_CREATED: 'AI_INSIGHT_CREATED',
  ENERGY_RECORD_CREATED: 'ENERGY_RECORD_CREATED',
  SETTINGS_CHANGED: 'SETTINGS_CHANGED',
});

module.exports = {
  ROLES,
  ORG_ROLES,
  WASTE_TRANSITIONS,
  PRODUCTION_BATCH_TRANSITIONS,
  ORDER_STATUS_TRANSITIONS,
  PAYMENT_STATUS_TRANSITIONS,
  DELIVERY_STATUS_TRANSITIONS,
  AUDIT_ACTIONS,
};
