import {
  type BuyerAccountProfile,
  type BuyerOrder,
  type BuyerProduct,
} from "@/types/buyer";

export const buyerProfileSeed: BuyerAccountProfile = {
  id: "buyer_001",
  firstName: "Amina",
  lastName: "Njoroge",
  email: "amina@greenmart.co.ke",
  phone: "+254712450901",
  role: "BUYER",
  status: "ACTIVE",
  organizationName: "GreenMart Supplies",
  joinedAt: "2026-02-14T08:30:00.000Z",
  lastActiveAt: "2026-04-22T09:18:00.000Z",
};

export const buyerProductsSeed: BuyerProduct[] = [
  {
    id: "bprd_001",
    name: "Black Soldier Fly Larvae",
    category: "LARVAE",
    unit: "kg",
    price: 540,
    availableQuantity: 320,
    availability: "IN_STOCK",
    description: "High-protein larvae feed suitable for poultry and aquaculture blends.",
    producerOrganization: "EcoLoop Nairobi",
    featured: true,
  },
  {
    id: "bprd_002",
    name: "Organic Fertilizer Mix",
    category: "FERTILIZER",
    unit: "bag",
    price: 880,
    availableQuantity: 76,
    availability: "IN_STOCK",
    description: "Nutrient-rich compost blend for horticulture and urban farming.",
    producerOrganization: "EcoLoop Nairobi",
    featured: true,
  },
  {
    id: "bprd_003",
    name: "Compressed Plastic Bricks",
    category: "PLASTIC_BRICKS",
    unit: "piece",
    price: 95,
    availableQuantity: 42,
    availability: "LOW_STOCK",
    description: "Durable recycled plastic bricks for landscaping and light construction use.",
    producerOrganization: "EcoLoop Nairobi",
  },
  {
    id: "bprd_004",
    name: "Recycled Garden Stakes",
    category: "GARDEN_STAKES",
    unit: "piece",
    price: 60,
    availableQuantity: 0,
    availability: "OUT_OF_STOCK",
    description: "Weather-resistant plant support stakes made from recycled plastic output.",
    producerOrganization: "EcoLoop Nairobi",
  },
  {
    id: "bprd_005",
    name: "Premium Larvae Feed Pack",
    category: "LARVAE",
    unit: "kg",
    price: 610,
    availableQuantity: 54,
    availability: "LOW_STOCK",
    description: "Screened larvae pack for premium feed formulations and controlled batch quality.",
    producerOrganization: "EcoLoop Nairobi",
  },
  {
    id: "bprd_006",
    name: "Fine Compost Fertilizer",
    category: "FERTILIZER",
    unit: "bag",
    price: 930,
    availableQuantity: 24,
    availability: "LOW_STOCK",
    description: "Refined fertilizer blend with lower moisture for improved shelf-life and transport.",
    producerOrganization: "EcoLoop Nairobi",
  },
];

export const buyerOrdersSeed: BuyerOrder[] = [
  {
    id: "bord_001",
    reference: "W2V-ORD-7812",
    createdAt: "2026-04-21T10:10:00.000Z",
    orderStatus: "FULFILLING",
    paymentStatus: "PAID",
    deliveryStatus: "IN_TRANSIT",
    totalAmount: 15120,
    itemCount: 2,
    buyerOrganization: "GreenMart Supplies",
    notes: "Deliver to Industrial Area warehouse dock B.",
    lines: [
      {
        productId: "bprd_001",
        productName: "Black Soldier Fly Larvae",
        quantity: 20,
        unit: "kg",
        unitPrice: 540,
        lineTotal: 10800,
      },
      {
        productId: "bprd_002",
        productName: "Organic Fertilizer Mix",
        quantity: 5,
        unit: "bag",
        unitPrice: 880,
        lineTotal: 4400,
      },
    ],
    timeline: [
      {
        id: "botl_001",
        title: "Order Placed",
        at: "2026-04-21T10:10:00.000Z",
        status: "PLACED",
      },
      {
        id: "botl_002",
        title: "Payment Confirmed",
        at: "2026-04-21T10:24:00.000Z",
        status: "PAID",
      },
      {
        id: "botl_003",
        title: "In Fulfillment",
        at: "2026-04-21T13:02:00.000Z",
        status: "FULFILLING",
        note: "Warehouse picking and packaging in progress.",
      },
      {
        id: "botl_004",
        title: "Out for Delivery",
        at: "2026-04-22T07:30:00.000Z",
        status: "IN_TRANSIT",
      },
    ],
  },
  {
    id: "bord_002",
    reference: "W2V-ORD-7789",
    createdAt: "2026-04-18T09:45:00.000Z",
    orderStatus: "COMPLETED",
    paymentStatus: "PAID",
    deliveryStatus: "DELIVERED",
    totalAmount: 9120,
    itemCount: 1,
    buyerOrganization: "GreenMart Supplies",
    lines: [
      {
        productId: "bprd_003",
        productName: "Compressed Plastic Bricks",
        quantity: 96,
        unit: "piece",
        unitPrice: 95,
        lineTotal: 9120,
      },
    ],
    timeline: [
      {
        id: "botl_005",
        title: "Order Placed",
        at: "2026-04-18T09:45:00.000Z",
        status: "PLACED",
      },
      {
        id: "botl_006",
        title: "Payment Confirmed",
        at: "2026-04-18T09:56:00.000Z",
        status: "PAID",
      },
      {
        id: "botl_007",
        title: "Delivered",
        at: "2026-04-19T12:10:00.000Z",
        status: "DELIVERED",
      },
    ],
  },
  {
    id: "bord_003",
    reference: "W2V-ORD-7742",
    createdAt: "2026-04-16T15:02:00.000Z",
    orderStatus: "CONFIRMED",
    paymentStatus: "PENDING",
    deliveryStatus: "PENDING",
    totalAmount: 3720,
    itemCount: 1,
    buyerOrganization: "GreenMart Supplies",
    lines: [
      {
        productId: "bprd_006",
        productName: "Fine Compost Fertilizer",
        quantity: 4,
        unit: "bag",
        unitPrice: 930,
        lineTotal: 3720,
      },
    ],
    timeline: [
      {
        id: "botl_008",
        title: "Order Placed",
        at: "2026-04-16T15:02:00.000Z",
        status: "PLACED",
      },
      {
        id: "botl_009",
        title: "Order Confirmed",
        at: "2026-04-16T15:30:00.000Z",
        status: "CONFIRMED",
      },
    ],
  },
];
