import {
  type AuditEvent,
  type Organization,
  type PlatformAnalyticsSummary,
  type PlatformUser,
} from "@/types/platform";

export const organizationsSeed: Organization[] = [
  {
    id: "org_eco_loop",
    name: "EcoLoop Nairobi",
    slug: "ecoloop-nairobi",
    description: "Urban waste collection and smart sorting network for Nairobi county.",
    status: "ACTIVE",
    createdAt: "2026-03-05T09:30:00.000Z",
    userCount: 24,
    hasOrgAdmin: true,
    onboardingStage: "READY",
    readinessScore: 96,
  },
  {
    id: "org_blue_cycle",
    name: "BlueCycle Cooperative",
    slug: "bluecycle-coop",
    description: "Community cooperative converting plastics into market-ready flakes.",
    status: "ACTIVE",
    createdAt: "2026-03-11T12:15:00.000Z",
    userCount: 17,
    hasOrgAdmin: true,
    onboardingStage: "SETUP_IN_PROGRESS",
    readinessScore: 79,
  },
  {
    id: "org_green_hub",
    name: "GreenHub Mombasa",
    slug: "greenhub-mombasa",
    description: "Coastal logistics and baling center for marine-bound materials.",
    status: "SUSPENDED",
    createdAt: "2026-02-20T15:05:00.000Z",
    userCount: 9,
    hasOrgAdmin: true,
    onboardingStage: "SETUP_IN_PROGRESS",
    readinessScore: 62,
  },
  {
    id: "org_value_bridge",
    name: "ValueBridge Kisumu",
    slug: "valuebridge-kisumu",
    description: "Regional aggregation network linking collectors to processors.",
    status: "ACTIVE",
    createdAt: "2026-03-19T08:20:00.000Z",
    userCount: 13,
    hasOrgAdmin: true,
    onboardingStage: "ADMIN_CREATED",
    readinessScore: 58,
  },
  {
    id: "org_circular_one",
    name: "CircularOne Uganda",
    slug: "circularone-uganda",
    description: "Cross-border circular commerce pilot and compliance readiness.",
    status: "DRAFT",
    createdAt: "2026-04-02T10:10:00.000Z",
    userCount: 2,
    hasOrgAdmin: false,
    onboardingStage: "NOT_STARTED",
    readinessScore: 24,
  },
  {
    id: "org_recraft",
    name: "ReCraft Rwanda",
    slug: "recraft-rwanda",
    description: "Municipal recovery partner focused on artisan-grade recycled outputs.",
    status: "ACTIVE",
    createdAt: "2026-04-08T11:40:00.000Z",
    userCount: 7,
    hasOrgAdmin: false,
    onboardingStage: "NOT_STARTED",
    readinessScore: 35,
  },
  {
    id: "org_future_bins",
    name: "FutureBins Dar",
    slug: "futurebins-dar",
    description: "Sensor-enabled bin infrastructure for dense city neighborhoods.",
    status: "ACTIVE",
    createdAt: "2026-04-10T09:00:00.000Z",
    userCount: 6,
    hasOrgAdmin: true,
    onboardingStage: "ADMIN_CREATED",
    readinessScore: 67,
  },
  {
    id: "org_zero_landfill",
    name: "ZeroLandfill Pilot",
    slug: "zerolandfill-pilot",
    description: "Pilot tenant testing enterprise reporting and traceability workflows.",
    status: "SUSPENDED",
    createdAt: "2026-01-27T14:10:00.000Z",
    userCount: 5,
    hasOrgAdmin: true,
    onboardingStage: "SETUP_IN_PROGRESS",
    readinessScore: 48,
  },
];

export const platformUsersSeed: PlatformUser[] = [
  {
    id: "user_super_1",
    firstName: "Amina",
    lastName: "Odede",
    email: "superadmin@waste2value.africa",
    phone: "+254712000001",
    role: "SUPER_ADMIN",
    status: "ACTIVE",
    createdAt: "2025-12-15T08:00:00.000Z",
    lastActiveAt: "2026-04-22T07:36:00.000Z",
  },
  {
    id: "user_super_2",
    firstName: "David",
    lastName: "Muriuki",
    email: "platform.ops@waste2value.africa",
    role: "SUPER_ADMIN",
    status: "ACTIVE",
    createdAt: "2026-01-02T09:20:00.000Z",
    lastActiveAt: "2026-04-21T16:44:00.000Z",
  },
  {
    id: "user_admin_1",
    firstName: "Joan",
    lastName: "Otieno",
    email: "admin@ecoloop.co.ke",
    role: "ORG_ADMIN",
    organizationId: "org_eco_loop",
    organizationName: "EcoLoop Nairobi",
    status: "ACTIVE",
    createdAt: "2026-03-06T10:00:00.000Z",
    lastActiveAt: "2026-04-22T06:18:00.000Z",
  },
  {
    id: "user_admin_2",
    firstName: "Peter",
    lastName: "Kamau",
    email: "admin@bluecycle.africa",
    role: "ORG_ADMIN",
    organizationId: "org_blue_cycle",
    organizationName: "BlueCycle Cooperative",
    status: "ACTIVE",
    createdAt: "2026-03-12T09:20:00.000Z",
    lastActiveAt: "2026-04-21T14:12:00.000Z",
  },
  {
    id: "user_admin_3",
    firstName: "Leah",
    lastName: "Kiptoo",
    email: "admin@greenhub.co",
    role: "ORG_ADMIN",
    organizationId: "org_green_hub",
    organizationName: "GreenHub Mombasa",
    status: "SUSPENDED",
    createdAt: "2026-02-22T12:10:00.000Z",
    lastActiveAt: "2026-03-17T09:40:00.000Z",
  },
  {
    id: "user_collector_1",
    firstName: "Brian",
    lastName: "Mwangi",
    email: "brian.collector@ecoloop.co.ke",
    role: "COLLECTOR",
    organizationId: "org_eco_loop",
    organizationName: "EcoLoop Nairobi",
    status: "ACTIVE",
    createdAt: "2026-03-17T08:45:00.000Z",
    lastActiveAt: "2026-04-21T11:11:00.000Z",
  },
  {
    id: "user_processor_1",
    firstName: "Mercy",
    lastName: "Njeri",
    email: "m.njeri@bluecycle.africa",
    role: "PROCESSOR",
    organizationId: "org_blue_cycle",
    organizationName: "BlueCycle Cooperative",
    status: "ACTIVE",
    createdAt: "2026-03-21T10:14:00.000Z",
    lastActiveAt: "2026-04-20T13:21:00.000Z",
  },
  {
    id: "user_buyer_1",
    firstName: "Kelvin",
    lastName: "Okoth",
    email: "buyer@valuebridge.co.ke",
    role: "BUYER",
    organizationId: "org_value_bridge",
    organizationName: "ValueBridge Kisumu",
    status: "INVITED",
    createdAt: "2026-04-10T11:05:00.000Z",
    lastActiveAt: "2026-04-10T11:07:00.000Z",
  },
  {
    id: "user_admin_4",
    firstName: "Naomi",
    lastName: "Wambui",
    email: "admin@futurebins.io",
    role: "ORG_ADMIN",
    organizationId: "org_future_bins",
    organizationName: "FutureBins Dar",
    status: "ACTIVE",
    createdAt: "2026-04-11T08:25:00.000Z",
    lastActiveAt: "2026-04-22T05:30:00.000Z",
  },
  {
    id: "user_admin_5",
    firstName: "Hassan",
    lastName: "Maalim",
    email: "admin@zerolandfill.com",
    role: "ORG_ADMIN",
    organizationId: "org_zero_landfill",
    organizationName: "ZeroLandfill Pilot",
    status: "SUSPENDED",
    createdAt: "2026-02-02T09:35:00.000Z",
    lastActiveAt: "2026-03-08T17:10:00.000Z",
  },
  {
    id: "user_collector_2",
    firstName: "Ruth",
    lastName: "Wairimu",
    email: "ruth@recraft.rw",
    role: "COLLECTOR",
    organizationId: "org_recraft",
    organizationName: "ReCraft Rwanda",
    status: "ACTIVE",
    createdAt: "2026-04-15T07:15:00.000Z",
    lastActiveAt: "2026-04-21T08:19:00.000Z",
  },
  {
    id: "user_processor_2",
    firstName: "James",
    lastName: "Kariuki",
    email: "jkariuki@ecoloop.co.ke",
    role: "PROCESSOR",
    organizationId: "org_eco_loop",
    organizationName: "EcoLoop Nairobi",
    status: "ACTIVE",
    createdAt: "2026-03-28T10:30:00.000Z",
    lastActiveAt: "2026-04-22T04:08:00.000Z",
  },
];

export const auditEventsSeed: AuditEvent[] = [
  {
    id: "audit_001",
    action: "ORGANIZATION_CREATED",
    actorName: "Amina Odede",
    actorEmail: "superadmin@waste2value.africa",
    entityType: "ORGANIZATION",
    entityId: "org_recraft",
    entityName: "ReCraft Rwanda",
    createdAt: "2026-04-08T11:40:00.000Z",
    ipAddress: "105.21.93.12",
    metadata: {
      source: "Super Admin UI",
      status: "DRAFT",
    },
  },
  {
    id: "audit_002",
    action: "USER_INVITED",
    actorName: "David Muriuki",
    actorEmail: "platform.ops@waste2value.africa",
    entityType: "USER",
    entityId: "user_buyer_1",
    entityName: "Kelvin Okoth",
    createdAt: "2026-04-10T11:06:00.000Z",
    ipAddress: "41.89.6.33",
    metadata: {
      role: "BUYER",
      organization: "ValueBridge Kisumu",
    },
  },
  {
    id: "audit_003",
    action: "ORGANIZATION_SUSPENDED",
    actorName: "Amina Odede",
    actorEmail: "superadmin@waste2value.africa",
    entityType: "ORGANIZATION",
    entityId: "org_zero_landfill",
    entityName: "ZeroLandfill Pilot",
    createdAt: "2026-04-12T09:30:00.000Z",
    ipAddress: "105.21.93.12",
    metadata: {
      reason: "Policy compliance pending",
    },
  },
  {
    id: "audit_004",
    action: "ORG_ADMIN_CREATED",
    actorName: "Amina Odede",
    actorEmail: "superadmin@waste2value.africa",
    entityType: "USER",
    entityId: "user_admin_4",
    entityName: "Naomi Wambui",
    createdAt: "2026-04-11T08:25:00.000Z",
    ipAddress: "105.21.93.12",
    metadata: {
      organization: "FutureBins Dar",
      delivery: "Temporary password issued",
    },
  },
  {
    id: "audit_005",
    action: "LOGIN_SUCCESS",
    actorName: "Amina Odede",
    actorEmail: "superadmin@waste2value.africa",
    entityType: "AUTH",
    entityId: "user_super_1",
    entityName: "Amina Odede",
    createdAt: "2026-04-22T07:36:00.000Z",
    ipAddress: "105.21.93.12",
    metadata: {
      channel: "web",
      rememberMe: "true",
    },
  },
  {
    id: "audit_006",
    action: "USER_SUSPENDED",
    actorName: "David Muriuki",
    actorEmail: "platform.ops@waste2value.africa",
    entityType: "USER",
    entityId: "user_admin_3",
    entityName: "Leah Kiptoo",
    createdAt: "2026-04-16T14:05:00.000Z",
    ipAddress: "41.89.6.33",
    metadata: {
      reason: "Escalated risk review",
    },
  },
  {
    id: "audit_007",
    action: "ORGANIZATION_REACTIVATED",
    actorName: "Amina Odede",
    actorEmail: "superadmin@waste2value.africa",
    entityType: "ORGANIZATION",
    entityId: "org_green_hub",
    entityName: "GreenHub Mombasa",
    createdAt: "2026-04-19T08:20:00.000Z",
    ipAddress: "105.21.93.12",
    metadata: {
      reviewer: "Platform Risk Desk",
    },
  },
  {
    id: "audit_008",
    action: "PLATFORM_SETTINGS_UPDATED",
    actorName: "David Muriuki",
    actorEmail: "platform.ops@waste2value.africa",
    entityType: "PLATFORM",
    entityId: "platform_main",
    entityName: "Waste2Value Platform",
    createdAt: "2026-04-20T12:00:00.000Z",
    ipAddress: "41.89.6.33",
    metadata: {
      setting: "session_timeout",
      previousValue: "8h",
      newValue: "12h",
    },
  },
];

export const analyticsSummarySeed: PlatformAnalyticsSummary = {
  growth: [
    { label: "Nov", organizations: 3, users: 18 },
    { label: "Dec", organizations: 4, users: 25 },
    { label: "Jan", organizations: 5, users: 37 },
    { label: "Feb", organizations: 6, users: 48 },
    { label: "Mar", organizations: 7, users: 66 },
    { label: "Apr", organizations: 8, users: 83 },
  ],
  roleDistribution: [
    { role: "SUPER_ADMIN", value: 2 },
    { role: "ORG_ADMIN", value: 5 },
    { role: "COLLECTOR", value: 2 },
    { role: "PROCESSOR", value: 2 },
    { role: "BUYER", value: 1 },
  ],
  onboarding: {
    completed: 2,
    inProgress: 4,
    pending: 2,
  },
};

export const superAdminProfile: PlatformUser = {
  id: "user_super_1",
  firstName: "Amina",
  lastName: "Odede",
  email: "superadmin@waste2value.africa",
  phone: "+254712000001",
  role: "SUPER_ADMIN",
  status: "ACTIVE",
  createdAt: "2025-12-15T08:00:00.000Z",
  lastActiveAt: "2026-04-22T07:36:00.000Z",
};
