import {
  type CollectionPoint,
  type GeoZone,
  type InventoryLot,
  type InventoryMovement,
  type Order,
  type OrgAccountProfile,
  type OrgAnalyticsSummary,
  type OrgTeamUser,
  type ProcessingBatch,
  type ProcessingCenter,
  type Product,
  type RedemptionRequest,
  type WalletTransaction,
  type WasteSubmission,
} from "@/types/org-admin";

export const orgAdminProfileSeed: OrgAccountProfile = {
  id: "org_admin_eco_1",
  firstName: "Joan",
  lastName: "Otieno",
  email: "admin@ecoloop.co.ke",
  role: "ORG_ADMIN",
  status: "ACTIVE",
  organizationName: "EcoLoop Nairobi",
  joinedAt: "2026-03-06T10:00:00.000Z",
  lastActiveAt: "2026-04-22T08:04:00.000Z",
};

export const orgTeamUsersSeed: OrgTeamUser[] = [
  {
    id: "team_001",
    firstName: "Joan",
    lastName: "Otieno",
    email: "admin@ecoloop.co.ke",
    role: "ORG_ADMIN",
    status: "ACTIVE",
    zone: "Central",
    assignment: "Operations Lead",
    joinedAt: "2026-03-06T10:00:00.000Z",
    lastActiveAt: "2026-04-22T08:04:00.000Z",
    stats: {},
  },
  {
    id: "team_002",
    firstName: "Brian",
    lastName: "Mwangi",
    email: "brian.collector@ecoloop.co.ke",
    role: "COLLECTOR",
    status: "ACTIVE",
    zone: "Central",
    assignment: "CBD Route",
    joinedAt: "2026-03-17T08:45:00.000Z",
    lastActiveAt: "2026-04-22T06:32:00.000Z",
    stats: { submissionsCount: 49, approvalRate: 91, creditsEarned: 1240 },
  },
  {
    id: "team_003",
    firstName: "Ruth",
    lastName: "Wairimu",
    email: "r.wairimu@ecoloop.co.ke",
    role: "COLLECTOR",
    status: "ACTIVE",
    zone: "Eastlands",
    assignment: "School Cluster",
    joinedAt: "2026-03-20T08:15:00.000Z",
    lastActiveAt: "2026-04-21T15:19:00.000Z",
    stats: { submissionsCount: 41, approvalRate: 86, creditsEarned: 1010 },
  },
  {
    id: "team_004",
    firstName: "James",
    lastName: "Kariuki",
    email: "jkariuki@ecoloop.co.ke",
    role: "PROCESSOR",
    status: "ACTIVE",
    zone: "Industrial",
    assignment: "Line A",
    joinedAt: "2026-03-28T10:30:00.000Z",
    lastActiveAt: "2026-04-22T07:10:00.000Z",
    stats: { batchesCompleted: 27, outputsProducedKg: 1940 },
  },
  {
    id: "team_005",
    firstName: "Mercy",
    lastName: "Njeri",
    email: "mercy.njeri@ecoloop.co.ke",
    role: "PROCESSOR",
    status: "ACTIVE",
    zone: "Industrial",
    assignment: "Line B",
    joinedAt: "2026-03-30T11:10:00.000Z",
    lastActiveAt: "2026-04-21T16:40:00.000Z",
    stats: { batchesCompleted: 24, outputsProducedKg: 1725 },
  },
  {
    id: "team_006",
    firstName: "Kelvin",
    lastName: "Okoth",
    email: "buyer@ecoloop.co.ke",
    role: "BUYER",
    status: "INVITED",
    zone: "Nairobi",
    assignment: "Procurement",
    joinedAt: "2026-04-10T11:05:00.000Z",
    lastActiveAt: "2026-04-10T11:07:00.000Z",
    stats: { ordersPlaced: 8, totalPurchased: 18450 },
  },
  {
    id: "team_007",
    firstName: "Samson",
    lastName: "Kiptoo",
    email: "samson.collector@ecoloop.co.ke",
    role: "COLLECTOR",
    status: "SUSPENDED",
    zone: "Westlands",
    assignment: "Retail Strip",
    joinedAt: "2026-03-26T09:25:00.000Z",
    lastActiveAt: "2026-04-11T12:32:00.000Z",
    stats: { submissionsCount: 14, approvalRate: 71, creditsEarned: 330 },
  },
];

export const wasteSubmissionsSeed: WasteSubmission[] = [
  {
    id: "sub_001",
    reference: "W2V-WS-2401",
    collectorId: "team_002",
    collectorName: "Brian Mwangi",
    wasteType: "ORGANIC",
    weightKg: 245,
    zone: "Central",
    collectionPoint: "Kenyatta Market Hub",
    tagCode: "TAG-8834",
    submittedAt: "2026-04-22T06:10:00.000Z",
    assignedProcessorId: "team_004",
    assignedProcessorName: "James Kariuki",
    status: "ASSIGNED",
    notes: "Source segregated from hospitality route.",
    images: [],
    timeline: [
      { status: "SUBMITTED", at: "2026-04-22T06:10:00.000Z", actor: "Brian Mwangi" },
      { status: "UNDER_REVIEW", at: "2026-04-22T06:30:00.000Z", actor: "Joan Otieno" },
      { status: "APPROVED", at: "2026-04-22T06:45:00.000Z", actor: "Joan Otieno" },
      { status: "ASSIGNED", at: "2026-04-22T07:00:00.000Z", actor: "Joan Otieno", note: "Assigned to Line A" },
    ],
    history: [
      {
        id: "hist_001",
        action: "SUBMISSION_RECEIVED",
        actor: "Brian Mwangi",
        at: "2026-04-22T06:10:00.000Z",
        details: "Uploaded with source and weight data.",
      },
      {
        id: "hist_002",
        action: "QUALITY_REVIEWED",
        actor: "Joan Otieno",
        at: "2026-04-22T06:30:00.000Z",
        details: "Segregation passed minimum quality threshold.",
      },
    ],
  },
  {
    id: "sub_002",
    reference: "W2V-WS-2396",
    collectorId: "team_003",
    collectorName: "Ruth Wairimu",
    wasteType: "PLASTIC",
    weightKg: 118,
    zone: "Eastlands",
    collectionPoint: "Umoja Collection Point",
    submittedAt: "2026-04-22T05:35:00.000Z",
    status: "UNDER_REVIEW",
    notes: "Mixed HDPE and PET bags.",
    images: [],
    timeline: [
      { status: "SUBMITTED", at: "2026-04-22T05:35:00.000Z", actor: "Ruth Wairimu" },
      { status: "UNDER_REVIEW", at: "2026-04-22T05:50:00.000Z", actor: "Joan Otieno" },
    ],
    history: [
      {
        id: "hist_003",
        action: "SUBMISSION_RECEIVED",
        actor: "Ruth Wairimu",
        at: "2026-04-22T05:35:00.000Z",
        details: "Collected from school cluster bins.",
      },
    ],
  },
  {
    id: "sub_003",
    reference: "W2V-WS-2390",
    collectorId: "team_002",
    collectorName: "Brian Mwangi",
    wasteType: "ORGANIC",
    weightKg: 210,
    zone: "Central",
    collectionPoint: "Railway Yard Point",
    submittedAt: "2026-04-21T15:40:00.000Z",
    assignedProcessorId: "team_005",
    assignedProcessorName: "Mercy Njeri",
    status: "IN_PROCESSING",
    notes: "Moisture acceptable.",
    images: [],
    timeline: [
      { status: "SUBMITTED", at: "2026-04-21T15:40:00.000Z", actor: "Brian Mwangi" },
      { status: "APPROVED", at: "2026-04-21T16:00:00.000Z", actor: "Joan Otieno" },
      { status: "ASSIGNED", at: "2026-04-21T16:10:00.000Z", actor: "Joan Otieno" },
      { status: "IN_PROCESSING", at: "2026-04-21T17:05:00.000Z", actor: "Mercy Njeri" },
    ],
    history: [
      {
        id: "hist_004",
        action: "PROCESSING_STARTED",
        actor: "Mercy Njeri",
        at: "2026-04-21T17:05:00.000Z",
        details: "Transferred to digestion lane B.",
      },
    ],
  },
  {
    id: "sub_004",
    reference: "W2V-WS-2385",
    collectorId: "team_007",
    collectorName: "Samson Kiptoo",
    wasteType: "GLASS",
    weightKg: 67,
    zone: "Westlands",
    collectionPoint: "Retail Strip Point",
    submittedAt: "2026-04-20T12:20:00.000Z",
    status: "REJECTED",
    notes: "Contaminated with mixed material.",
    images: [],
    timeline: [
      { status: "SUBMITTED", at: "2026-04-20T12:20:00.000Z", actor: "Samson Kiptoo" },
      { status: "UNDER_REVIEW", at: "2026-04-20T12:44:00.000Z", actor: "Joan Otieno" },
      { status: "REJECTED", at: "2026-04-20T12:50:00.000Z", actor: "Joan Otieno", note: "Contamination above threshold" },
    ],
    history: [
      {
        id: "hist_005",
        action: "REJECTED",
        actor: "Joan Otieno",
        at: "2026-04-20T12:50:00.000Z",
        details: "Rejected due to contamination above policy threshold.",
      },
    ],
  },
  {
    id: "sub_005",
    reference: "W2V-WS-2379",
    collectorId: "team_003",
    collectorName: "Ruth Wairimu",
    wasteType: "PAPER",
    weightKg: 144,
    zone: "Eastlands",
    collectionPoint: "Mihango Point",
    submittedAt: "2026-04-19T09:30:00.000Z",
    assignedProcessorId: "team_004",
    assignedProcessorName: "James Kariuki",
    status: "PROCESSED",
    notes: "Dry and compacted.",
    images: [],
    timeline: [
      { status: "SUBMITTED", at: "2026-04-19T09:30:00.000Z", actor: "Ruth Wairimu" },
      { status: "APPROVED", at: "2026-04-19T09:55:00.000Z", actor: "Joan Otieno" },
      { status: "ASSIGNED", at: "2026-04-19T10:05:00.000Z", actor: "Joan Otieno" },
      { status: "IN_PROCESSING", at: "2026-04-19T11:20:00.000Z", actor: "James Kariuki" },
      { status: "PROCESSED", at: "2026-04-19T14:40:00.000Z", actor: "James Kariuki" },
    ],
    history: [
      {
        id: "hist_006",
        action: "BATCH_CLOSED",
        actor: "James Kariuki",
        at: "2026-04-19T14:40:00.000Z",
        details: "Converted to compacted paper block output.",
      },
    ],
  },
];

export const processingBatchesSeed: ProcessingBatch[] = [
  {
    id: "batch_001",
    reference: "BCH-901",
    processorName: "James Kariuki",
    wasteType: "ORGANIC",
    inputKg: 210,
    outputKg: 162,
    status: "ACTIVE",
    startedAt: "2026-04-21T17:05:00.000Z",
  },
  {
    id: "batch_002",
    reference: "BCH-899",
    processorName: "Mercy Njeri",
    wasteType: "PLASTIC",
    inputKg: 190,
    outputKg: 145,
    status: "COMPLETED",
    startedAt: "2026-04-20T10:00:00.000Z",
    completedAt: "2026-04-20T17:15:00.000Z",
  },
  {
    id: "batch_003",
    reference: "BCH-904",
    processorName: "Mercy Njeri",
    wasteType: "ORGANIC",
    inputKg: 185,
    outputKg: 0,
    status: "QUEUED",
    startedAt: "2026-04-22T09:00:00.000Z",
  },
];

export const productsSeed: Product[] = [
  {
    id: "prod_001",
    name: "Premium BSF Larvae",
    category: "LARVAE",
    unit: "kg",
    price: 460,
    status: "ACTIVE",
    stockAvailable: 410,
    description: "High-protein larvae for feed applications.",
  },
  {
    id: "prod_002",
    name: "Soil Booster Fertilizer",
    category: "FERTILIZER",
    unit: "bag",
    price: 2200,
    status: "ACTIVE",
    stockAvailable: 72,
    description: "Organic fertilizer blend from processed organics.",
  },
  {
    id: "prod_003",
    name: "Recycled Plastic Brick",
    category: "PLASTIC_BRICKS",
    unit: "piece",
    price: 95,
    status: "ACTIVE",
    stockAvailable: 1200,
    description: "Durable construction blocks made from sorted plastics.",
  },
  {
    id: "prod_004",
    name: "Garden Stakes",
    category: "GARDEN_STAKES",
    unit: "piece",
    price: 35,
    status: "DRAFT",
    stockAvailable: 0,
    description: "Lightweight stakes for agri and landscaping use.",
  },
];

export const inventoryLotsSeed: InventoryLot[] = [
  {
    id: "lot_001",
    productId: "prod_001",
    productName: "Premium BSF Larvae",
    lotCode: "LRV-APR-11",
    quantity: 160,
    unit: "kg",
    location: "Cold Bay A",
    expiresAt: "2026-05-02T00:00:00.000Z",
    status: "GOOD",
  },
  {
    id: "lot_002",
    productId: "prod_002",
    productName: "Soil Booster Fertilizer",
    lotCode: "FRT-APR-06",
    quantity: 22,
    unit: "bag",
    location: "Rack F2",
    status: "LOW",
  },
  {
    id: "lot_003",
    productId: "prod_003",
    productName: "Recycled Plastic Brick",
    lotCode: "PLB-APR-04",
    quantity: 380,
    unit: "piece",
    location: "Yard Bay C",
    status: "GOOD",
  },
  {
    id: "lot_004",
    productId: "prod_002",
    productName: "Soil Booster Fertilizer",
    lotCode: "FRT-MAR-28",
    quantity: 8,
    unit: "bag",
    location: "Rack F1",
    status: "RISK",
  },
];

export const inventoryMovementsSeed: InventoryMovement[] = [
  {
    id: "mov_001",
    productName: "Premium BSF Larvae",
    lotCode: "LRV-APR-11",
    type: "IN",
    quantity: 100,
    unit: "kg",
    reason: "Batch output posted",
    actor: "James Kariuki",
    createdAt: "2026-04-21T18:00:00.000Z",
  },
  {
    id: "mov_002",
    productName: "Soil Booster Fertilizer",
    lotCode: "FRT-MAR-28",
    type: "OUT",
    quantity: 12,
    unit: "bag",
    reason: "Order fulfillment",
    actor: "Joan Otieno",
    createdAt: "2026-04-21T15:20:00.000Z",
  },
  {
    id: "mov_003",
    productName: "Recycled Plastic Brick",
    lotCode: "PLB-APR-04",
    type: "ADJUSTMENT",
    quantity: 15,
    unit: "piece",
    reason: "Cycle count correction",
    actor: "Joan Otieno",
    createdAt: "2026-04-20T11:40:00.000Z",
  },
];

export const ordersSeed: Order[] = [
  {
    id: "ord_2201",
    buyerName: "FarmHub Supplies",
    productCount: 2,
    total: 36400,
    paymentStatus: "PAID",
    deliveryStatus: "IN_TRANSIT",
    createdAt: "2026-04-22T07:35:00.000Z",
    lines: [
      { productName: "Premium BSF Larvae", quantity: 40, unitPrice: 460 },
      { productName: "Soil Booster Fertilizer", quantity: 8, unitPrice: 2200 },
    ],
  },
  {
    id: "ord_2198",
    buyerName: "GreenBuild Co",
    productCount: 1,
    total: 22800,
    paymentStatus: "PENDING",
    deliveryStatus: "PENDING",
    createdAt: "2026-04-21T14:20:00.000Z",
    lines: [{ productName: "Recycled Plastic Brick", quantity: 240, unitPrice: 95 }],
  },
  {
    id: "ord_2191",
    buyerName: "RuralAgri Market",
    productCount: 1,
    total: 15400,
    paymentStatus: "PAID",
    deliveryStatus: "DELIVERED",
    createdAt: "2026-04-20T10:15:00.000Z",
    lines: [{ productName: "Soil Booster Fertilizer", quantity: 7, unitPrice: 2200 }],
  },
];

export const redemptionRequestsSeed: RedemptionRequest[] = [
  {
    id: "red_001",
    userName: "Brian Mwangi",
    amount: 420,
    requestedItem: "Mobile airtime",
    createdAt: "2026-04-22T06:42:00.000Z",
    status: "PENDING",
  },
  {
    id: "red_002",
    userName: "Ruth Wairimu",
    amount: 680,
    requestedItem: "Cash payout",
    createdAt: "2026-04-21T09:20:00.000Z",
    status: "APPROVED",
  },
  {
    id: "red_003",
    userName: "Samson Kiptoo",
    amount: 210,
    requestedItem: "Airtime",
    createdAt: "2026-04-18T13:00:00.000Z",
    status: "REJECTED",
  },
];

export const walletTransactionsSeed: WalletTransaction[] = [
  {
    id: "txn_001",
    type: "CREDIT_ISSUED",
    userName: "Brian Mwangi",
    amount: 160,
    createdAt: "2026-04-22T06:12:00.000Z",
    note: "Credits for organic batch W2V-WS-2401",
  },
  {
    id: "txn_002",
    type: "REDEMPTION_APPROVED",
    userName: "Ruth Wairimu",
    amount: 680,
    createdAt: "2026-04-21T10:00:00.000Z",
    note: "Approved by org admin",
  },
  {
    id: "txn_003",
    type: "REDEMPTION_REJECTED",
    userName: "Samson Kiptoo",
    amount: 210,
    createdAt: "2026-04-18T13:20:00.000Z",
    note: "Insufficient verifiable submissions",
  },
];

export const orgAnalyticsSummarySeed: OrgAnalyticsSummary = {
  wasteByType: [
    { type: "ORGANIC", weightKg: 1720 },
    { type: "PLASTIC", weightKg: 960 },
    { type: "PAPER", weightKg: 620 },
    { type: "METAL", weightKg: 290 },
    { type: "GLASS", weightKg: 215 },
  ],
  wasteByZone: [
    { zone: "Central", weightKg: 1390 },
    { zone: "Eastlands", weightKg: 1045 },
    { zone: "Westlands", weightKg: 530 },
    { zone: "Industrial", weightKg: 840 },
  ],
  approvalsTrend: [
    { label: "Week 1", approved: 31, rejected: 6 },
    { label: "Week 2", approved: 36, rejected: 4 },
    { label: "Week 3", approved: 42, rejected: 5 },
    { label: "Week 4", approved: 47, rejected: 3 },
  ],
  processorOutputTrend: [
    { label: "Week 1", outputKg: 530 },
    { label: "Week 2", outputKg: 620 },
    { label: "Week 3", outputKg: 710 },
    { label: "Week 4", outputKg: 790 },
  ],
  creditsIssuedTrend: [
    { label: "Week 1", credits: 4200 },
    { label: "Week 2", credits: 5100 },
    { label: "Week 3", credits: 5600 },
    { label: "Week 4", credits: 6080 },
  ],
  revenueTrend: [
    { label: "Week 1", revenue: 79000 },
    { label: "Week 2", revenue: 88000 },
    { label: "Week 3", revenue: 102000 },
    { label: "Week 4", revenue: 114500 },
  ],
};

export const geoZonesSeed: GeoZone[] = [
  { id: "zone_001", name: "Central", status: "ACTIVE", collectors: 2 },
  { id: "zone_002", name: "Eastlands", status: "ACTIVE", collectors: 1 },
  { id: "zone_003", name: "Westlands", status: "ACTIVE", collectors: 1 },
  { id: "zone_004", name: "Industrial", status: "INACTIVE", collectors: 0 },
];

export const collectionPointsSeed: CollectionPoint[] = [
  { id: "cp_001", name: "Kenyatta Market Hub", zone: "Central", status: "ACTIVE" },
  { id: "cp_002", name: "Railway Yard Point", zone: "Central", status: "ACTIVE" },
  { id: "cp_003", name: "Umoja Collection Point", zone: "Eastlands", status: "ACTIVE" },
  { id: "cp_004", name: "Retail Strip Point", zone: "Westlands", status: "INACTIVE" },
];

export const processingCentersSeed: ProcessingCenter[] = [
  { id: "pc_001", name: "EcoLoop Processing Yard", zone: "Industrial", status: "ACTIVE" },
  { id: "pc_002", name: "Compost Line B", zone: "Industrial", status: "ACTIVE" },
  { id: "pc_003", name: "Plastic Mould Unit", zone: "Central", status: "ACTIVE" },
];
