import {
  type ProcessorAccountProfile,
  type ProcessorAssignment,
  type ProcessorBatch,
  type ProcessorPerformanceData,
  type ProcessorRedemptionRequest,
  type ProcessorWalletTransaction,
} from "@/types/processor";

export const processorProfileSeed: ProcessorAccountProfile = {
  id: "processor_001",
  firstName: "James",
  lastName: "Kariuki",
  email: "jkariuki@ecoloop.co.ke",
  phone: "+254701551020",
  role: "PROCESSOR",
  status: "ACTIVE",
  organizationName: "EcoLoop Nairobi",
  processingCenter: "EcoLoop Processing Yard",
  joinedAt: "2026-03-28T10:30:00.000Z",
  lastActiveAt: "2026-04-22T08:32:00.000Z",
};

export const processorAssignmentsSeed: ProcessorAssignment[] = [
  {
    id: "pass_001",
    reference: "W2V-WS-2401",
    collectorName: "Brian Mwangi",
    wasteType: "ORGANIC",
    weightKg: 245,
    zone: "Central",
    processingCenter: "EcoLoop Processing Yard",
    collectionPoint: "Kenyatta Market Hub",
    tagCode: "TAG-8834",
    notes: "Sorted and low contamination.",
    assignedAt: "2026-04-22T07:00:00.000Z",
    status: "AWAITING_RECEIPT",
    processorName: "James Kariuki",
    timeline: [
      {
        id: "ptl_001",
        title: "Assigned",
        at: "2026-04-22T07:00:00.000Z",
        status: "AWAITING_RECEIPT",
        actor: "Joan Otieno",
      },
    ],
    history: [
      {
        id: "phs_001",
        action: "ASSIGNMENT_CREATED",
        at: "2026-04-22T07:00:00.000Z",
        actor: "Joan Otieno",
        details: "Submission assigned to James Kariuki for receipt confirmation.",
      },
    ],
  },
  {
    id: "pass_002",
    reference: "W2V-WS-2390",
    collectorName: "Brian Mwangi",
    wasteType: "ORGANIC",
    weightKg: 210,
    zone: "Central",
    processingCenter: "EcoLoop Processing Yard",
    collectionPoint: "Railway Yard Point",
    assignedAt: "2026-04-21T16:12:00.000Z",
    status: "IN_PROCESSING",
    processorName: "James Kariuki",
    timeline: [
      {
        id: "ptl_002",
        title: "Assigned",
        at: "2026-04-21T16:12:00.000Z",
        status: "AWAITING_RECEIPT",
        actor: "Joan Otieno",
      },
      {
        id: "ptl_003",
        title: "Receipt Confirmed",
        at: "2026-04-21T16:34:00.000Z",
        status: "RECEIVED",
        actor: "James Kariuki",
      },
      {
        id: "ptl_004",
        title: "Processing Started",
        at: "2026-04-21T17:05:00.000Z",
        status: "IN_PROCESSING",
        actor: "James Kariuki",
      },
    ],
    history: [
      {
        id: "phs_002",
        action: "PROCESSING_STARTED",
        at: "2026-04-21T17:05:00.000Z",
        actor: "James Kariuki",
        details: "Moved to digestion lane A and linked to batch BCH-901.",
      },
    ],
  },
  {
    id: "pass_003",
    reference: "W2V-WS-2379",
    collectorName: "Ruth Wairimu",
    wasteType: "PLASTIC",
    weightKg: 144,
    zone: "Eastlands",
    processingCenter: "Plastic Mould Unit",
    collectionPoint: "Mihango Point",
    assignedAt: "2026-04-19T10:05:00.000Z",
    status: "PROCESSED",
    processorName: "James Kariuki",
    timeline: [
      {
        id: "ptl_005",
        title: "Assigned",
        at: "2026-04-19T10:05:00.000Z",
        status: "AWAITING_RECEIPT",
        actor: "Joan Otieno",
      },
      {
        id: "ptl_006",
        title: "Receipt Confirmed",
        at: "2026-04-19T10:32:00.000Z",
        status: "RECEIVED",
        actor: "James Kariuki",
      },
      {
        id: "ptl_007",
        title: "Processing Started",
        at: "2026-04-19T11:20:00.000Z",
        status: "IN_PROCESSING",
        actor: "James Kariuki",
      },
      {
        id: "ptl_008",
        title: "Processed",
        at: "2026-04-19T14:40:00.000Z",
        status: "PROCESSED",
        actor: "James Kariuki",
      },
    ],
    history: [
      {
        id: "phs_003",
        action: "BATCH_COMPLETED",
        at: "2026-04-19T14:40:00.000Z",
        actor: "James Kariuki",
        details: "Output recorded and assignment closed.",
      },
    ],
  },
  {
    id: "pass_004",
    reference: "W2V-WS-2396",
    collectorName: "Ruth Wairimu",
    wasteType: "PLASTIC",
    weightKg: 118,
    zone: "Eastlands",
    processingCenter: "Plastic Mould Unit",
    collectionPoint: "Umoja Collection Point",
    assignedAt: "2026-04-22T06:20:00.000Z",
    status: "RECEIVED",
    processorName: "James Kariuki",
    timeline: [
      {
        id: "ptl_009",
        title: "Assigned",
        at: "2026-04-22T06:20:00.000Z",
        status: "AWAITING_RECEIPT",
        actor: "Joan Otieno",
      },
      {
        id: "ptl_010",
        title: "Receipt Confirmed",
        at: "2026-04-22T07:12:00.000Z",
        status: "RECEIVED",
        actor: "James Kariuki",
      },
    ],
    history: [
      {
        id: "phs_004",
        action: "RECEIPT_CONFIRMED",
        at: "2026-04-22T07:12:00.000Z",
        actor: "James Kariuki",
        details: "Input quality accepted at receiving dock.",
      },
    ],
  },
];

export const processorBatchesSeed: ProcessorBatch[] = [
  {
    id: "pbatch_001",
    reference: "BCH-901",
    wasteType: "ORGANIC",
    inputWeightKg: 210,
    processingCenter: "EcoLoop Processing Yard",
    processorName: "James Kariuki",
    assignmentIds: ["pass_002"],
    inputReferences: ["W2V-WS-2390"],
    outputs: [
      {
        id: "pout_001",
        outputType: "LARVAE",
        quantity: 162,
        unit: "kg",
        recordedAt: "2026-04-22T08:02:00.000Z",
        notes: "High-quality larvae yield.",
      },
      {
        id: "pout_002",
        outputType: "FERTILIZER",
        quantity: 11,
        unit: "bag",
        recordedAt: "2026-04-22T08:15:00.000Z",
      },
    ],
    status: "ACTIVE",
    startedAt: "2026-04-21T17:05:00.000Z",
    notes: "Digestor lane A running steady.",
    timeline: [
      {
        id: "btl_001",
        title: "Batch Created",
        at: "2026-04-21T17:05:00.000Z",
        status: "ACTIVE",
        actor: "James Kariuki",
      },
      {
        id: "btl_002",
        title: "Outputs Recorded",
        at: "2026-04-22T08:15:00.000Z",
        status: "ACTIVE",
        actor: "James Kariuki",
      },
    ],
    history: [
      {
        id: "bhs_001",
        action: "OUTPUT_RECORDED",
        at: "2026-04-22T08:15:00.000Z",
        actor: "James Kariuki",
        details: "Larvae and fertilizer outputs captured.",
      },
    ],
  },
  {
    id: "pbatch_002",
    reference: "BCH-894",
    wasteType: "PLASTIC",
    inputWeightKg: 144,
    processingCenter: "Plastic Mould Unit",
    processorName: "James Kariuki",
    assignmentIds: ["pass_003"],
    inputReferences: ["W2V-WS-2379"],
    outputs: [
      {
        id: "pout_003",
        outputType: "PLASTIC_BRICKS",
        quantity: 280,
        unit: "piece",
        recordedAt: "2026-04-19T14:10:00.000Z",
      },
      {
        id: "pout_004",
        outputType: "GARDEN_STAKES",
        quantity: 75,
        unit: "piece",
        recordedAt: "2026-04-19T14:20:00.000Z",
      },
    ],
    status: "COMPLETED",
    startedAt: "2026-04-19T11:20:00.000Z",
    completedAt: "2026-04-19T14:40:00.000Z",
    timeline: [
      {
        id: "btl_003",
        title: "Batch Created",
        at: "2026-04-19T11:20:00.000Z",
        status: "ACTIVE",
        actor: "James Kariuki",
      },
      {
        id: "btl_004",
        title: "Batch Completed",
        at: "2026-04-19T14:40:00.000Z",
        status: "COMPLETED",
        actor: "James Kariuki",
      },
    ],
    history: [
      {
        id: "bhs_002",
        action: "BATCH_CLOSED",
        at: "2026-04-19T14:40:00.000Z",
        actor: "James Kariuki",
        details: "All outputs recorded and inventory posted.",
      },
    ],
  },
  {
    id: "pbatch_003",
    reference: "BCH-906",
    wasteType: "PLASTIC",
    inputWeightKg: 118,
    processingCenter: "Plastic Mould Unit",
    processorName: "James Kariuki",
    assignmentIds: ["pass_004"],
    inputReferences: ["W2V-WS-2396"],
    outputs: [],
    status: "DRAFT",
    startedAt: "2026-04-22T09:05:00.000Z",
    notes: "Awaiting full line setup.",
    timeline: [
      {
        id: "btl_005",
        title: "Batch Drafted",
        at: "2026-04-22T09:05:00.000Z",
        status: "DRAFT",
        actor: "James Kariuki",
      },
    ],
    history: [
      {
        id: "bhs_003",
        action: "BATCH_DRAFT_CREATED",
        at: "2026-04-22T09:05:00.000Z",
        actor: "James Kariuki",
        details: "Draft created from received plastic input.",
      },
    ],
  },
];

export const processorWalletTransactionsSeed: ProcessorWalletTransaction[] = [
  {
    id: "pwt_001",
    type: "CREDIT_EARNED",
    amount: 220,
    status: "SUCCESS",
    context: "Credits from completed batch BCH-894",
    reference: "BCH-894",
    createdAt: "2026-04-19T14:45:00.000Z",
  },
  {
    id: "pwt_002",
    type: "CREDIT_EARNED",
    amount: 180,
    status: "SUCCESS",
    context: "Credits from output update BCH-901",
    reference: "BCH-901",
    createdAt: "2026-04-22T08:20:00.000Z",
  },
  {
    id: "pwt_003",
    type: "REDEMPTION_REQUESTED",
    amount: -300,
    status: "PENDING",
    context: "Redemption request for cash payout",
    createdAt: "2026-04-21T13:12:00.000Z",
  },
  {
    id: "pwt_004",
    type: "REDEMPTION_APPROVED",
    amount: -210,
    status: "SUCCESS",
    context: "Approved airtime redemption",
    createdAt: "2026-04-18T09:14:00.000Z",
  },
];

export const processorRedemptionRequestsSeed: ProcessorRedemptionRequest[] = [
  {
    id: "pred_001",
    amount: 300,
    requestedItem: "Cash payout",
    status: "PENDING",
    createdAt: "2026-04-21T13:12:00.000Z",
  },
  {
    id: "pred_002",
    amount: 210,
    requestedItem: "Airtime",
    status: "APPROVED",
    createdAt: "2026-04-18T08:40:00.000Z",
  },
];

export const processorPerformanceSeed: ProcessorPerformanceData = {
  completedBatches: 12,
  processedSubmissions: 34,
  totalOutputQuantity: 1460,
  creditsEarned: 2040,
  reliabilityScore: 93,
  processingStreak: 6,
  weeklyProduction: [
    { label: "Week 1", batches: 2, outputs: 210 },
    { label: "Week 2", batches: 3, outputs: 330 },
    { label: "Week 3", batches: 3, outputs: 420 },
    { label: "Week 4", batches: 4, outputs: 500 },
  ],
  insights: [
    "Batch closeout speed improved by 18% over the last month.",
    "Plastic line outputs are stable with lower rework incidents.",
    "Consistent receipt confirmation is boosting workflow throughput.",
  ],
};

export const processorCentersSeed = [
  "EcoLoop Processing Yard",
  "Plastic Mould Unit",
  "Compost Line B",
];

export const processorZonesSeed = ["Central", "Eastlands", "Industrial"];
